<a href="https://colab.research.google.com/github/cesaroliveiragoes/Machine-Learning-Data-Science-Classes/blob/main/Machine_Learning_and_Data_Science_Class_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error as MAE
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/diogenesjusto/FIAP/master/SHIFT/Data/pib.csv")
df

,Unnamed: 0,ANO_MES,PIB,BRL,BRP,BRT,SLP,SPP,SPT,PRL,...,PIBi3,PIBi4,PIBi5,PIBi6,PIBi7,PIBi8,PIBi9,PIBi10,PIBi11,PIBi12
0,1,jan/04,103.09,109.19,108.67,109.08,102.84,114.27,105.38,127.49,...,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03,100.00
1,2,fev/04,102.05,95.65,104.52,97.63,90.76,109.83,94.99,96.60,...,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03
2,3,mar/04,110.43,91.69,125.53,99.26,89.78,133.24,99.43,83.79,...,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70
3,4,abr/04,106.77,95.36,118.34,100.49,94.58,123.55,101.02,91.79,...,103.09,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17
4,5,mai/04,108.08,92.47,121.49,98.96,91.34,128.32,99.55,85.73,...,102.05,103.09,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,134,fev/15,144.42,147.35,133.73,143.57,147.81,148.96,147.54,157.30,...,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92,151.44,148.92
134,135,mar/15,151.68,149.64,163.27,152.09,154.87,179.07,159.56,147.28,...,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92,151.44
135,136,abr/15,147.03,153.81,149.93,152.28,161.21,164.74,161.16,162.21,...,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92
136,137,mai/15,148.94,149.66,153.03,149.82,157.03,169.39,158.76,149.06,...,144.42,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49
137,138,jun/15,147.37,146.13,147.98,145.84,152.96,162.92,153.86,144.14,...,151.68,144.42,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92

In [ ]:
# Separação de treino e teste
treino = df.iloc[0:126]
teste = df.iloc[126:138]

In [ ]:
# Regressão
Y_treino = treino.iloc[:,[2]]
X = ['BRL']
X_treino = treino.loc[:,X]
mod = LinearRegression()
mod.fit(X_treino, Y_treino)
# Analise de coeficientes
print(mod.coef_)
print(mod.intercept_)

[[0.64930687]]
[51.97004633]

Modelo PIB, BRL
Y = AX + B
PIB = A*BRL + B
PIB = 0,64*brl + 51,97

In [ ]:
teste.head(1)

,Unnamed: 0,ANO_MES,PIB,BRL,BRP,BRT,SLP,SPP,SPT,PRL,...,PIBi3,PIBi4,PIBi5,PIBi6,PIBi7,PIBi8,PIBi9,PIBi10,PIBi11,PIBi12
126,127,jul/14,154.34,150.55,165.58,153.8,154.34,181.79,159.98,160.34,...,150.92,151.44,148.92,151.43,150.3,153.2,156.88,153.5,156.98,156.05

In [ ]:
# Calculando primeira previsão na mão

PIBJUL14 = 0.64*150.55 + 51.97

#Valor da previsão PIB para julho 2014
print(PIBJUL14)

#Valor Real do PIB em julho de 2014
teste.PIB.head(1)

# Erro de previsão (Valor Real - Valor Previsto)
148.32 - 154.34

148.322

-6.02000000000001

In [ ]:
# Calculo de erro com python
X_teste = teste.loc[:,X]
Y_prev = mod.predict(X_teste)
Y_real = teste.loc[:,['PIB']]
Y_real
erro = Y_prev - Y_real

# Previsão de erro
print(MAE(Y_real, Y_prev))
#print(np.mean(abs(erro)))

5.294479600275532