<a href="https://colab.research.google.com/github/cesaroliveiragoes/Machine-Learning-Data-Science-Classes/blob/main/Machine_Learning_and_Data_Science_Class_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/diogenesjusto/FIAP/master/dados/classifier.csv")

df

,"id)""",result,Score1,Score2,Frequency1,Frequency2,Amount,Net,LTV,Source,Gender,AgeRange,CustomerType
0,1,#N/D,NaN,0.0,NaN,NaN,NaN,0.0,0.00,2.0,M,35_to_49,1.0
1,2,1,13.0229,0.0,NaN,NaN,NaN,112.0,1.61,2.0,F,NaN,2.0
2,3,1,96.4988,0.0,NaN,NaN,NaN,1319.0,530.78,2.0,F,35_to_49,2.0
3,4,#N/D,NaN,0.0,NaN,NaN,NaN,0.0,0.00,2.0,F,35_to_49,1.0
4,5,1,23.3103,0.0,NaN,NaN,NaN,266.0,6.45,2.0,F,18_to_34,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,0,30.8796,0.0,NaN,NaN,NaN,287.0,5.61,2.0,F,35_to_49,2.0
29996,29997,0,6.2247,6.0,95.0,3.0,1772.0,1280.0,55.77,5.0,F,35_to_49,5.0
29997,29998,1,4.5620,4.2,59.0,1.0,480.0,597.0,14.95,5.0,M,35_to_49,4.0
29998,29999,1,20.1870,6.7,196.0,6.0,4986.0,237.0,95.71,5.0,M,35_to_49,5.0
29999,30000,1,3.9566,0.0,NaN,NaN,NaN,1.0,0.09,2.0,M,35_to_49,2.0

In [ ]:
df.shape

(30000, 13)

In [ ]:
# Média
df[['Score1']].mean()

Score1    36.79789
dtype: float64

In [ ]:
# Mediana
df[['Score1']].median()

Score1    33.9267
dtype: float64

In [ ]:
# Desvio Padrão
df[['Score1']].std()

Score1    24.638989
dtype: float64

1) A geração de uma amostra não aleatória de 3000 linhas e a demonstração
de que não é adequada utilizá-la

In [ ]:
# não-aleatória
a1 = df.iloc[0:2999, :]
a1.shape

(2999, 13)

In [ ]:
a1[['Score1']].mean()
# 0.01%

Score1    36.783179
dtype: float64

In [ ]:
a1[['Score1']].median()
#  4.11%

Score1    32.5325
dtype: float64

In [ ]:
a1[['Score1']].std()
# 1% (acima)

Score1    25.076307
dtype: float64

In [ ]:
# Esta pode ser adadequada pois as estatísticas descritivas (média, mediana, desvio padrão) estão abaixo dos 5%
# Sendo assim, considerando a variável "Score1" do df, o resultado representa a população

2) A geração de uma amostra aleatória de 3000 linhas e a demonstração que é
adequado utilizá-la como amostra representativa

In [ ]:
# aleatória
a2 = df.sample(3000, random_state=4)
a2

,"id)""",result,Score1,Score2,Frequency1,Frequency2,Amount,Net,LTV,Source,Gender,AgeRange,CustomerType
7254,7255,0,5.9768,2.4,35.0,NaN,NaN,391.0,6.55,5.0,M,35_to_49,2.0
371,372,0,59.0683,0.0,NaN,NaN,NaN,0.0,47.94,2.0,M,35_to_49,2.0
17542,17543,0,17.7124,0.7,3.0,NaN,NaN,100.0,2.56,5.0,M,18_to_34,2.0
25320,25321,1,48.2892,0.0,NaN,NaN,NaN,225.0,14.97,2.0,F,50_to_59,2.0
12041,12042,1,32.4282,9.2,59.0,15.0,16032.0,445.0,275.89,5.0,F,35_to_49,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5908,5909,0,50.6450,4.8,101.0,15.0,47987.0,21560.0,679.03,1.0,M,35_to_49,4.0
11952,11953,1,2.0241,0.0,NaN,NaN,NaN,50.0,0.85,2.0,I,NaN,2.0
14529,14530,1,23.0498,1.8,6.0,NaN,NaN,300.0,5.13,5.0,F,18_to_34,3.0
3478,3479,1,61.5429,0.0,NaN,NaN,NaN,62.0,0.89,2.0,M,60_or_higher,2.0
2510,2511,1,43.4024,2.0,7.0,NaN,NaN,450.0,7.70,5.0,F,18_to_34,3.0

In [ ]:
a2[['Score1']].mean()
# 3.1%

Score1    36.025755
dtype: float64

In [ ]:
a2[['Score1']].median()
# 2.2%

Score1    33.5251
dtype: float64

In [ ]:
a2[['Score1']].std()
# 0.95%

Score1    24.405892
dtype: float64

In [ ]:
# Esta também pode ser a forma adequada pois as estatísticas estão todas abaixo de 5%, porém, a amostra não-aleatória possui valores menores mostrando um nível de confiança maior.
# Sendo assim, considerando a variável "Score1" do df, o resultado também representa a população, mas, com um nível de confiança menor.

In [ ]:
# Integrantes
# Cesar Oliveira Goes - RM: 98119
# Fiama dos Santos Trajano - RM: 97885
# Karina Maciel Palmeira - RM: 551770