<a href="https://colab.research.google.com/github/cesaroliveiragoes/Machine-Learning-Data-Science-Classes/blob/main/Machine_Learning_and_Data_Science_Exs_06_pt_2_Autoregressao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# INTEGRANTE
# NOME: CESAR OLIVEIRA GOES
# RM: 98119

In [ ]:
# Exercício 09/04 - parte 1

# Carga de bibliotecas
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error as MAE
import statsmodels.api as sm

# Carga de dados
df = pd.read_csv("https://raw.githubusercontent.com/diogenesjusto/FIAP/master/SHIFT/Data/pib.csv")

# Separação de treino e teste
treino = df.iloc[0:126]
teste = df.iloc[126:138]

# Regressão
Y_treino = treino.iloc[:,[2]]
#X = ['BRL', 'BRP'] # Regressão Linear Simples
# Modelo AutoRegressivo
X = ['PIBi1', 'PIBi2', 'PIBi4', 'PIBi12']
X_treino = treino.loc[:,X]
mod = LinearRegression()
mod.fit(X_treino, Y_treino)

print(mod.score(X_treino,Y_treino))

# Cálculo de erro com python
X_teste = teste.loc[:,X]
Y_prev = mod.predict(X_teste)
Y_real = teste.loc[:,['PIB']]
Erro = Y_prev - Y_real

# Erro de previsão
print(MAE(Y_real, Y_prev))

mod_sm = sm.OLS(Y_treino, X_treino).fit()
print(mod_sm.summary())

In [ ]:
#NC = 1 - p_valor
1-0.78

In [ ]:
# Como construir colunas com lag
df['PIBi1_'] = df['PIB'].shift(1)
df['PIBi2_'] = df['PIB'].shift(2)

df.head(15)

In [ ]:
# Exercício 1 - 02/04/2024

df = pd.read_csv("https://raw.githubusercontent.com/diogenesjusto/FIAP/master/Gradua%C3%A7%C3%A3o/dados/desafio_baba.csv")

# Como construir colunas com lag
df['venda1'] = df['venda'].shift(1)
df['venda2'] = df['venda'].shift(2)
df['venda3'] = df['venda'].shift(3)
df['venda4'] = df['venda'].shift(4)
df['venda5'] = df['venda'].shift(5)
df['venda6'] = df['venda'].shift(6)
df['venda7'] = df['venda'].shift(7)

#df.boxplot(['venda'], by='weekday')

# Separação de treino e teste
treino = df.iloc[7:334]
teste = df.iloc[334:365]

Y_treino = treino.loc[:,['venda']]
# Modelo AutoRegressivo
X = ['venda1', 'venda3', 'venda4']
X_treino = treino.loc[:,X]
mod = LinearRegression()
mod.fit(X_treino, Y_treino)

# Análise de coeficientes
print(mod.coef_)
print(mod.intercept_)

mod_sm = sm.OLS(Y_treino, X_treino).fit()
print(mod_sm.summary())

# Cálculo de erro com python
X_teste = teste.loc[:,X]
Y_prev = mod.predict(X_teste)
Y_real = teste.loc[:,['venda']]
Erro = Y_prev - Y_real

# Erro de previsão
print(MAE(Y_real, Y_prev))

,Unnamed: 0,X,date,mes,weekday,margem,venda,desconto,outdesc,outmg,venda1,venda2,venda3
0,1,1,20140801,agosto,sexta-feira,0.406111,110042.460,9190.907534,0,0,NaN,NaN,NaN
1,2,2,20140802,agosto,sabado,0.416022,58377.320,5713.043012,0,0,110042.460,NaN,NaN
2,3,3,20140803,agosto,domingo,0.431993,64635.390,8621.708915,0,0,58377.320,110042.46,NaN
3,4,4,20140804,agosto,segunda-feira,0.409216,140417.321,18312.965640,0,0,64635.390,58377.32,110042.46
4,5,5,20140805,agosto,terca-feira,0.449648,149700.286,19942.741300,0,0,140417.321,64635.39,58377.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,392,392,20150827,agosto,quinta-feira,0.451562,NaN,5846.133551,0,0,NaN,NaN,NaN
392,393,393,20150828,agosto,sexta-feira,0.472608,NaN,2657.847261,0,0,NaN,NaN,NaN
393,394,394,20150829,agosto,sabado,0.385612,NaN,269.530000,0,0,NaN,NaN,NaN
394,395,395,20150830,agosto,domingo,0.495615,NaN,3434.838118,0,0,NaN,NaN,NaN
395,396,396,20150831,agosto,segunda-feira,0.391486,NaN,2122.636306,0,0,NaN,NaN,NaN

In [ ]:
# Exercício 2 - 09/04/2024

# Carga de dados
df = pd.read_csv("https://raw.githubusercontent.com/diogenesjusto/FIAP/master/SHIFT/Data/pib.csv")

# Contruis Lags de BRL e BRP
df['BRPi1'] = df['BRP'].shift(1)
df['BRPi2'] = df['BRP'].shift(2)
df['BRLi1'] = df['BRL'].shift(1)
df['BRLi2'] = df['BRL'].shift(2)

# Separação de treino e teste
treino = df.iloc[2:126]
teste = df.iloc[126:138]

# Regressão BRL
Y_treino = treino.loc[:,['BRL']]
# Modelo AutoRegressivo
X = ['BRLi1', 'BRLi2']
X_treino = treino.loc[:,X]
mod = LinearRegression()
mod.fit(X_treino, Y_treino)
# Previsão em teste
X_teste = teste.loc[:,X]
BRL_prev = mod.predict(X_teste)

# Regressão BRP
Y_treino = treino.loc[:,['BRP']]
# Modelo AutoRegressivo
X = ['BRPi1', 'BRPi2']
X_treino = treino.loc[:,X]
mod = LinearRegression()
mod.fit(X_treino, Y_treino)
# Previsão em teste
X_teste = teste.loc[:,X]
BRP_prev = mod.predict(X_teste)

dfPrev = pd.DataFrame(BRL_prev, columns=['BRL'])
dfPrev['BRP'] = BRP_prev

[[-0.03064081]]
[20148747.64725125]
20095710.75369594

In [ ]:
# Modelo Multivariado BRL e BRP
Y_treino = treino.loc[:,['PIB']]
# Modelo Multivariado
X = ['BRL', 'BRP']
X_treino = treino.loc[:,X]
mod = LinearRegression()
mod.fit(X_treino, Y_treino)

# Previsão em teste
#X_teste = teste.loc[:,X]
X_teste = dfPrev
Y_prev = mod.predict(X_teste)

# Cálculo de erro com python
Y_real = teste.loc[:,['PIB']]
Erro = Y_prev - Y_real

# Erro de previsão
print(MAE(Y_real, Y_prev))

,Unnamed: 0,X,date,mes,weekday,margem,venda,desconto,outdesc,outmg,venda1,venda2,venda3
337,338,338,20150704,julho,sabado,0.414695,39549.3,3702.52,0,0,43166.14,56121.85,66499.88